name: PHP Tests

on:
  push:
    branches: [ main, 7.4-support ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: PHP Versions
      run: ls /etc/php && ls /usr/bin | grep php

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: composer-cache
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: PHP Lint
        run: composer lint
      - name: Run 8.1 Test Suite
        run: php8.1 vendor/bin/phpunit --no-coverage
      - name: Run 8.0 Test Suite
        run: php8.0 vendor/bin/phpunit --no-coverage
      - name: Run 7.4 Test Suite
        continue-on-error: true
        run: php7.4 vendor/bin/phpunit --no-coverage
